### PR TITLE
Data labels for bar charts

### PR DESCRIPTION
**Pull request by cipri-p**
**What kind of change does this PR introduce? (check one with "x")**

- [ ]  Bugfix
- [x]  Feature
- [ ]  Code style update (formatting, local variables)
- [ ]  Refactoring (no functional changes, no api changes)
- [ ]  Build related changes
- [ ]  CI related changes
- [ ]  Other... Please describe:

**What is the current behavior? (You can also link to an open issue here)**

#745 #610

**What is the new behavior?**

The vertical/horizontal bar charts (normal, grouped and stacked) have a new attribute now called ShowDataLabel.

**Does this PR introduce a breaking change? (check one with "x")**

- [ ] Yes
- [x]  No

### CODE REVIEW

**Comment by mansoorsiddiqui** [comment]
Hey, can you upload a screenshot of what this looks like? Was hoping to implement something like this for my bar charts and pie charts so that it shows the value on top.

**Comment by cipri-p** [comment]
@mansoorsiddiqui Here are some print screens. If you want to play with use the following in you package.json:
 "@swimlane/ngx-charts": "git+https://github.com/cipri-p/ngx-charts",

label1
label3
label2

**Comment by hakimio** [comment]
Would be nice to be able to adjust label distance from the bars.

**Comment by cipri-p** [comment]
@hakimio: Do you mean more like a padding or more like over the bars?

**Comment by hakimio** [comment]
The distance from the label to its bar. For vertical bar charts that would be bottom padding, for horizontal bar charts, it would be left padding.

**Comment by mansoorsiddiqui** [comment]
Very cool! Does this implementation work for pie charts aa well?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hakimio** [comment]
@mansoorsiddiqui it literary says in the title "Data labels for BAR charts"...

**Comment by cmbkla** [comment]
I need this in my life.

**Comment by mansoorsiddiqui** [comment]
@hakimio Oh wow, thanks for pointing that out! So helpful. 

You can modify the placement/font of the labels by overriding the textDataLabel css class in your component:
`.textDataLabel {
	font-size: 18px !important;
	transform: translate(-7px, -7px) !important;
}`

**Comment by marjan-georgiev** [comment]
@cipri-p thank you! Could you revert the changes to the release folder please? Those are only generated when we release a new version.

**Comment by cipri-p** [comment]
@marjan-georgiev done. Also implemented the axis offset based on the data label width/height.

**Comment by marjan-georgiev** [comment]
Thanks @cipri-p, this looks really good.
There are 2 alignment issues I am seeing:

1. The Y axis is offset to the right, and does not align with the chart data. This is your branch:

image

This is master:

image

2. The negative data label on the vertical stacked bar chart is overlapping the x axis.

image

**Comment by cipri-p** [comment]
@marjan-georgiev sorry for that. Just pushed a fix for both.

**Comment by marjan-georgiev** [comment]
Looks good! Great work @cipri-p, thank you!

**Comment by andreisrob** [comment]
@cipri-p This is a really great addition.  Thank you.  
It would be nice if we had the option to display the label so that it is parallel to the top line of the vertical bar instead of the default slant.  Custom formatting would be great as well, i.e. color, font-size, etc.

**Comment by sumegha26** [comment]
Hi @cipri-p , @marjan-georgiev 

I want to override the transform rotation added on data label, to override textDataLabel I used ::ng-deep. This is working as expected on chrome but for IE11 as css svg transformation is not supported on IE9+ , I have accessed textDataLabel by querying DOM and updated transform but current transformation is added in ngOnchanges() every time library's transform get applied. As a workaround I added my transform override method in setTimeout()

Is there any other way to resolve this ? or can we added support to toggle DataLabel rotation ?

**Pull request merged**
