### PR TITLE
[Feature] Tooltip template to Number Card Chart

### PR DESCRIPTION
**Pull request by KingDarBoja**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x] Feature
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Check #1236

**What is the new behavior?**
You can pass tooltip templates to the number card chart. This fixes the #1236 issue as requested and also enforces types on number card chart.

**I will add to the docs the new inputs on my next commit.**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by CAspeling** [comment]
I thought tooltips for numbercards existed ages ago. We've been using it for months.

image

**Comment by KingDarBoja** [comment]
@CAspeling Those are default browser tooltips, this PR let you build custom tooltips by passing the template to the component input.

So you get the feature of tooltip customisation, you can arrange the content and also display plus format the data as you can see with the other charts at the official documentation.

**Comment by ghugan** [comment]
Hi, Is this commit added successfully? I cant be able to see this codes in version 12.0.0 and above..

**Comment by KingDarBoja** [comment]
@ghugan As you can notice at the PR state, it hasn't been merged into master hence you won't be able to use it on any version of the package.

**Comment by ghugan** [comment]
@KingDarBoja i see..So when will this feature be added?

**Comment by KingDarBoja** [comment]
No idea to be honest, I am not an official maintainer, just a casual contributor.

I would fix the conflicting files in order to make this PR ready to merge.

**Pull request closed without merging**
