### PR TITLE
Tooltip text/bar line

### PR DESCRIPTION
**Pull request by JoshSchoen**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Not able to customize tools tips for bar, line and area charts. Issue referring to Issue #320.

**What is the new behavior?**
Enables the creation of custom tool tips for line, bar, area type charts. Also added the ability to show actuals on Normalized bar charts.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
Pending approval, what are the best practices for applying CSS to the custom tool tips classes. Should that be done globally or at a component level?

### CODE REVIEW

**Comment by JoshSchoen** [comment]
@amcdnl, @marjan-georgiev have you had a chance to look at this? I'm developing in [Covalent](https://github.com/Teradata/covalent) and we're getting to the point where will need to have this functionality soon. I'lll take on any feedback items so just let me know. Thanks, really appreciate your efforts!

**Comment by marjan-georgiev** [comment]
@JoshSchoen this looks good, thanks! I am working on a feature allowing passing ng-template for charts to use as tooltips. Let's work together on combining these two features so there are no breaking changes later. I'm going to do a PR for that soon and we can work on integrating both solutions. Thanks again!

**Comment by JoshSchoen** [comment]
@marjan-georgiev sounds great! Happy to jump in  on whatever just let me know how I can help. Excited to get this going!

**Comment by marjan-georgiev** [comment]
I merged the https://github.com/swimlane/ngx-charts/pull/399 PR into master. It should cover the same use cases as this PR, so I will close this one. Please let me know if you think anything else needs to be added.

Thank you for the contribution and reviews!

**Pull request closed without merging**
