### PR TITLE
Add log scale axes to line-chart-component

### PR DESCRIPTION
**Pull request by matteson**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
There is no way to log scale the x and y axes.

**What is the new behavior?**
ngx-charts-line-chart supports binding
[xAxisTransform]="xAxisTransform"
[yAxisTransform]="yAxisTransform"
where the transform can be either 'linear' or 'log'.

If the x values of the series are not numbers, then 'log' has no effect on the x-axis.

The demo has been updated to include this as an option in the line-chart.
**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
I'm trying to port an app to use ngx-charts and need this in the timeline of a few days to be relevant. I can run from my fork for the time being, but I don't have the bandwidth to implement this across other chart types in the near future. 

This seems to introduce a naming inconsistency between LineSeriesComponent and LineChartComponent of scaleType and xScaleType respectively. I didn't want to wade excessively into naming changes here, so would appreciate some guidance. 

I'm not attached to the property names.

### CODE REVIEW

**Comment by amcdnl** [comment]
Please don't include the build, it makes diff/merge a nightmare.

**Comment by matteson** [comment]
Whoops! Sorry about that. Wasn't thinking when I did the commits of the build.

**Comment by matteson** [comment]
Reverted the build inclusion.

**Comment by matteson** [comment]
Closing pull request so I can do some things with our internal master branch. Will open another PR on a feature branch.

**Pull request closed without merging**
