### PR TITLE
no date conversion for name-value at series-tooltip

### PR DESCRIPTION
**Pull request by tobigit**
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
The "name"-value is converted to locale date-string without time-part using toLocaleDateString-function.
See also: https://github.com/swimlane/ngx-charts/issues/457

**What is the new behavior?**
The "name"-value of the tooltip-model contains now the raw date-value as it is. So you can do any date-conversion as you want.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
New Pull Request with actual release 6.0.2

### CODE REVIEW

**Comment by amcdnl** [comment]
In the future please don't commit the build files :)

**Comment by sebastianlaag** [comment]
We have the same problem and appreciate if someone could merge the pull request :)

**Comment by marjan-georgiev** [comment]
@tobigit can you remove the changes to the release folder please?

**Comment by tobigit** [comment]
@marjan-georgiev I have reverted the changes of release folder.

**Comment by marjan-georgiev** [comment]
Thanks! 👍

**Pull request merged**
