### PR TITLE
Feat(tooltips) Allow defining custom ng-tempaltes for tooltips

### PR DESCRIPTION
**Pull request by marjan-georgiev**
**What kind of change does this PR introduce?** (check one with "x")
- [x] Feature

**What is the new behavior?**
A custom ng-template can be passed to the charts and displayed as html inside the tooltips:
The template needs to have the `#tooltipTemplate` in order to be recognized by the chart. The data that can be used inside the template can be obtained through the `item` property in the context. It usually has the following format `{series, name, value}`, though it may be different - depending on the chart type.

Example:
```
<ngx-charts-bar-vertical
  [scheme]="colorScheme"
  ...
  [results]="single">

  <ng-template #tooltipTemplate let-item="item">
    <h1>
      {{getFlag(item.name)}}
    </h1>
    <h2>{{item.name}}: {{item.value}}</h2>
  </ng-template>

</ngx-charts-bar-vertical>
```

image

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by marjan-georgiev** [comment]
@JoshSchoen can you take a look at this and let me know if it covers your use cases?
It still needs a tooltipTemplate for the series tooltips in line/area charts, but I will be adding those too.

**Comment by JoshSchoen** [comment]
@marjan-georgiev this looks great!  I like the ng-template implementation better.

**Comment by j--wong** [comment]
@marjan-georgiev I'm using the tooltipTemplate to display custom tooltip like in your example.  However, `item` variable is always `undefined`.  Am I missing anything?  I am using it in `ngx-charts-bar-horizontal-stacked` chart.  Thanks

**Comment by rafalkondratsolid** [comment]
I think that property item was refactored to model. 
Take a look at working example for custom tooltipTemplate:
```
<ng-template #tooltipTemplate let-model="model">
    <h1>
      {{getFlag(model.name)}}
    </h1>
    <h2>{{model.name}}: {{model.value}}</h2>
</ng-template>
```

**Comment by j--wong** [comment]
Ah, got it! I was using "item" instead of "model".

It's all working now. Thanks.

**Comment by sueess** [comment]
On the line chart I get two different tooltips depending where the cursor is.

**Comment by grimace** [comment]
feeling kind of thick headed here, but is this available in 6.0.0?  I'm getting:

`Can't bind to 'seriesTooltipTemplate' since it isn't a known property of 'ngx-charts-line-chart'.`

looks like it's there but how would I use this?

**Comment by grimace** [comment]
NM,

I just didn't get this, but if someone else is struggling with this, the trick is to put the actual template inside the chart selector:

```
 <ngx-charts-line-chart id='chart' 
    ...
    ...
    ...
   >
    <ng-template #tooltipTemplate let-model="model">
          bla bla bla
    </ng-template>
 </ngx-charts-line-chart>

```

**Comment by wachpwnski** [comment]
How do you also get the percentage that is in the default template for the normalized bar?

**Comment by btroncone** [comment]
@marjan-georgiev Hello, to echo @wachpwnski question I also have a use-case for accessing the percentage data within a normalize chart but it does not seem like this is available within the custom template.

For instance, I would like to make a small modification to the template to be `[name]: [percentage] ([value])`. From what I can tell (also attempting to dig through the code) there doesn't seem to be an easy way to accomplish this outside of creating an extra map, calculating what is already calculated by the chart (displayed in standard tooltip) then combining that with the data that is accessible within the custom template.

Is there something obvious I am missing here, or anything you can suggest to more easily accomplish this task? Thanks in advance!

**Comment by krist-jin** [comment]
@grimace Hi I have the same issue but moving the template inside doesn't help. See plunker: https://plnkr.co/edit/U7JE8d?p=preview

**Pull request merged**
