### PR TITLE
chore: update to angular 15

### PR DESCRIPTION
**Pull request by bobbyg603**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

```
Error: Failed to initialize Angular compilation - The target entry-point "@swimlane/ngx-charts" has missing dependencies:
 - rxjs/Observable
 - rxjs/add/observable/fromEvent
 - rxjs/add/operator/debounceTime
```

**What is the new behavior?**

Library can be used by Angular 15 projects

**Does this PR introduce a breaking change?** (check one with "x")
- [x] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

Applications should update to Angular 15

**Other information**:

### CODE REVIEW

**Comment by adamrzw-apprentice** [comment]
+1 Would like to get an Angular 15 compatible version to avoid legacy peer deps

**Comment by bobbyg603** [comment]
@bobbyg603 we just published a mirror of this package built for Angular 15 that you can install via npm https://www.npmjs.com/package/@bugsplat/ngx-charts

**Comment by manast** [comment]
> @bobbyg603 we just published a mirror of this package built for Angular 15 that you can install via npm https://www.npmjs.com/package/@bugsplat/ngx-charts

Do you have a github repo where we can check your changes vs this repo?

**Comment by bobbyg603** [comment]
> > @bobbyg603 we just published a mirror of this package built for Angular 15 that you can install via npm https://www.npmjs.com/package/@bugsplat/ngx-charts
> 
> Do you have a github repo where we can check your changes vs this repo?

https://github.com/BugSplat-Git/ngx-charts/tree/ng-15

**Comment by manast** [comment]
@bobbyg603 Unfortunately I am getting the same error with your version as the official package.

```
TypeError: node.transition is not a function. (In 'node.transition()', 'node.transition' is undefined)
updatePathEl — bugsplat-ngx-charts.mjs:6794
update — bugsplat-ngx-charts.mjs:6783
ngOnChanges — bugsplat-ngx-charts.mjs:6771
rememberChangeHistoryAndInvokeOnChangesHook — core.mjs:1574
callHook — core.mjs:2498
callHooks — core.mjs:2457
executeInitAndCheckHooks — core.mjs:2408
refreshView — core.mjs:10434
refreshEmbeddedViews — core.mjs:11434
refreshView — core.mjs:10443
refreshEmbeddedViews — core.mjs:11434
refreshView — core.mjs:10443
refreshComponent — core.mjs:11480
refreshChildComponents — core.mjs:10210
refreshView — core.mjs:10469
refreshComponent — core.mjs:11480
refreshChildComponents — core.mjs:10210
refreshView — core.mjs:10469
refreshComponent — core.mjs:11480
refreshChildComponents — core.mjs:10210
refreshView — core.mjs:10469
refreshEmbeddedViews — core.mjs:11434
refreshView — core.mjs:10443
refreshComponent — core.mjs:11480
refreshChildComponents — core.mjs:10210
refreshView — core.mjs:10469
detectChangesInternal — core.mjs:11624
detectChanges — core.mjs:12115
tick — core.mjs:25402
```

**Comment by bobbyg603** [comment]
@manast we are using this package in production, so we are pretty sure it works. Ensure you're using the latest version of node 18, delete `node_modules`, and reinstall.

**Comment by manast** [comment]
@bobbyg603 hmm, ok, in my codebase it does not work. I will try on a clean angular 15 demo app instead.

**Comment by manast** [comment]
@bobbyg603 ok, so with the demo angular app created with ng cli it works without the error, however, it also works with the standard @swimlane version 😂

**Comment by GitHubish** [comment]
Same problem, but I have NodeJS 18.

**Comment by manast** [comment]
@GitHubish in my case I made it work using npm instead of yarn...

**Comment by mukundkatpatal** [comment]
Hi all,
Hi all, I forked this repo [here](https://github.com/mukundkatpatal/ngx-charts-15/blob/master/README.md) and created a package compatible with angular 15.
The package is [here](https://www.npmjs.com/package/@stoick/ngx-15-charts)
I am looking for more contributors and maintainers for my repo.

**Comment by bobbyg603** [comment]
Hi @surya-pabbineedi! We have been using this branch in production for a bit and it has been working well. Any hope of getting this merged?

**Pull request closed without merging**
