### PR TITLE
[Feature] Box Chart

### LINKED ISSUE #1242: Add box plot chart type
**Is your feature request related to a problem? Please describe.**
Has a box plot chart type been considered for addition?

**Describe the solution you'd like**
I'd like a basic box plot chart type, as seen here - https://plot.ly/javascript/box-plots/

**Describe alternatives you've considered**
I don't really see a reasonable way to implement this as a combo chart, so I think this probably needs to be its own chart type

### PR DESCRIPTION
**Pull request by KingDarBoja**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Fixes #1242.

**What is the new behavior?**
A new box chart with basic info on hover. I will add the data as bullet points at the side as extra feature as soon as I finish the chart design.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

**Other information**:
Also, this chart has some new working inputs like as `stroke` and `strokeWidth` to define the colour and line width of box lines including whiskers.

### CODE REVIEW

**Comment by KingDarBoja** [comment]
@marjan-georgiev I love the new lgtm bot 🍰

**Comment by AlDrag** [comment]
Any progress on getting this reviewed and merged?

**Comment by EtienneLamoureux** [comment]
I'm also very interested in this feature! Hopefully it can move forward soon.

**Comment by KingDarBoja** [comment]
I will take a look and fix any conflicts so this can be merged as soon as possible.

**Comment by KingDarBoja** [comment]
Closing this PR as a new one was made :)

**Pull request closed without merging**
