### PR TITLE
Fixing timeline selection

### LINKED ISSUE #1575: Timeline not working on version 17.0.0
**Describe the bug**
For line or area charts timeline does not work

**To Reproduce**
1. Create a line chart using version 17.0.0. Use temporal data type for X axis.
2. Set "timeline" to "true"
3. as chart is rendered interact with timeline to zoom in on particular area of the chart
4. The appearance of the main chart does not change

**Expected behavior**
The main area of the chart should update accordingly

**ngx-charts version**
"@swimlane/ngx-charts": "17.0.0"

### PR DESCRIPTION
**Pull request by Zoraiyo**
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Code style update (formatting, local variables)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Fixes #1575 

**What is the new behavior?**
Selection in timeline will change x-axis range in the main chart again. 

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by jesuspa17** [comment]
:partying_face:

**Review by Hypercubed — APPROVED** [review]

**Comment by Zoraiyo** [comment]
Hi @Hypercubed, 
thanks for merging the pull request. Can you tell when those changes will be available in a new version on NPM?

**Comment by laksan1** [comment]
Good day. Saw you fixed the timeline. Thank you so much. I have a problem, I don't understand how to set the timeline in my project. Updated "@ swimlane / ngx-charts" to version "18.0.1". Please give a hint on how to make the timeline appear. In my project all diagrams are built on ngx.
image

**Comment by Zoraiyo** [comment]
Hi @laksan1,

you should delete your comment here in this pull request and move that question to issues. 
I will delete this comment as well, when yours is moved.
Thanks

**Pull request merged**
