### PR TITLE
fixed AoT build issue for Angular 5

### PR DESCRIPTION
**Pull request by playerx**
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
ng build -prod fails:
```
ERROR in TypeError: Cannot read property 'version' of null
    at readMetadataFile (/Users/ez/Github/highland-ui/node_modules/@angular/compiler-cli/src/transformers/metadata_reader.js:66:29)...
```

**What is the new behavior?**
ng build -prod works

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by HitomiTenshi** [comment]
@playerx Release files get overwritten every time a new build is made, this PR only fixes the problem for the current version. Future versions will be broken again after running `npm run package`.

@marjan-georgiev I wouldn't merge this PR at its current state.

**Comment by HitomiTenshi** [comment]
Fixed in #644 
Polyfills needed an export.

**Comment by playerx** [comment]
@HitomiTenshi  got it, cool that its fixed already, I'll wait for next release.

Thanks

**Comment by HitomiTenshi** [comment]
@playerx Could you try this test build to see if AoT works for you with it?

Run `npm install github:HitomiTenshi/ngx-charts#angular5` to try this custom build.

**Comment by Koslun** [comment]
@HitomiTenshi I tested it and it solved the build error for our project.

Will use this until it's merged with the next release or if it's somehow fixed in Angular before that.

**Comment by marjan-georgiev** [comment]
Released in 7.0.1

**Pull request closed without merging**
