### PR TITLE
Allow rxjs 7.4.x

### LINKED ISSUE #1699: Angular 13 support
Any idea when Angular 13 will be supported? We're trying to update to Angular 13 but a few libraries have conflicting peer dependencies. It would be great to bump the versions and target Angular 13 if not difficult. Thank you very much.

### PR DESCRIPTION
**Pull request by denisfalqueto**
This is the current version for Angular 13, se that's needed for new and upgraded apps.

**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [X] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

Angular 13 apps can't use ngx-charts because they use rxjs 7.4 and ngx-charts only accepts rxjs 6.x.

Fixes #1699 

**What is the new behavior?**

Applications that use ngx-charts will work in rxjs 6 and 7.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by Stwissel** [comment]
+1

**Comment by NashIlli** [comment]
+1

**Comment by johannesnormannjensen** [comment]
+1

**Comment by martibenn** [comment]
done on this PR : https://github.com/swimlane/ngx-charts/pull/1714

**Pull request closed without merging**
