### PR TITLE
add paddingInnerPercent as proportions for both bar and group paddings

### PR DESCRIPTION
**Pull request by lvanngo**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

Bar and Group Padding are currently not responsive.

**What is the new behavior?**
Added option to specify the padding proportion to bar width as well as group width between 0 and 1 in order to be responsive.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by marjan-georgiev** [comment]
We already have these options. They are called `barPadding` and `groupPadding` respectively and they accept a numeric input in pixels.

You can see them in the documentation https://swimlane.gitbooks.io/ngx-charts/content/charts/bar-vertical-2d.html

And it's also in the demo page.

**Comment by lvanngo** [comment]
The existing barPadding and groupPadding are in pixels, not percent.  If you let the chart adapt the parent size by setting view to undefined, these values are not responsive.  That is why I added these percentage based options.  Thoughts?

**Comment by marjan-georgiev** [comment]
We made a conscious decision to use absolute padding (px) instead of relative (percent), because we felt it gave us better control in most of the cases.

**Comment by lvanngo** [comment]
But on a page where I'm using flexbox to control responsive settings on multiple screens with many charts which resize dynamically, the only way to control consistent look and feel on multiple screens is with proportions, not absolute values.

**Comment by marjan-georgiev** [comment]
I see your point. I don't like that we would have two separate inputs for the same thing. So maybe combine them with the existing ones and make them accept both relative and absolute values?

Example:

`[barPadding]="8"`  - 8px (for backwards compatibility)
`[barPadding]="8px"` - 8px
`[barPadding]="8%" - 8%

**Comment by lvanngo** [comment]
O.K.  Thanks for the suggestion.  Will do.

**Comment by lvanngo** [comment]
Closing this as it's too old.  Will open another one.

**Comment by Hypercubed** [comment]
Hello @lvanngo , please have a look at  #301

We should implement the same for bar charts.

**Pull request closed without merging**
