### PR TITLE
min max for heatmap added

### PR DESCRIPTION
**Pull request by abdullahsaleem93**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [ x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:
**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ x] No

**Other information**:
This was merged in 7.0.x but not 7.x
https://github.com/swimlane/ngx-charts/issues/602
https://github.com/swimlane/ngx-charts/pull/877

### CODE REVIEW

**Comment by TheParad0X** [comment]
Is this PR still active? Why are there so many PRs waiting? This feature is important

**Comment by abdullahsaleem93** [comment]
@TheParad0X this PR is already merged in mater and 7.0.x branch.
https://github.com/swimlane/ngx-charts/pull/875
https://github.com/swimlane/ngx-charts/pull/878

**Comment by TheParad0X** [comment]
Where is this documented? I cannot find it here https://swimlane.gitbook.io/ngx-charts/examples/heat-map-chart

**Comment by abdullahsaleem93** [comment]
I guess the documentation was not updated. There is a `max` property, just like the gauge chart

**Pull request closed without merging**
