### PR TITLE
fix: tooltip display on iOS

### LINKED ISSUE #1228: no tooltips display in iOS
Hi, 
we are using the charts cross plattform. But the tooltips of the charts are not triggered on the iPad, iOS version 12.1
Even in the [demo page](https://swimlane.github.io/ngx-charts/#/ngx-charts/bar-vertical) the tooltips are not displayed in this iOS version.

**Expected behavior**
displaying of tooltips on all plattforms

**Demo**
https://swimlane.github.io/ngx-charts/#/ngx-charts/bar-vertical

### PR DESCRIPTION
**Pull request by nodro7**
Add `touchstart` HostListener
Add `touchstart` to tooltip ShowTypes
Prevent additional mouse events (`click`) from hiding the tooltip on iOS

Fixes #1228

**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

Tooltips don't display in various chart types on iOS devices (e.g, bar chart)

https://github.com/swimlane/ngx-charts/issues/1228

**What is the new behavior?**

Tooltips do display on iOS devices

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by swondo** [comment]
When are we merging this change :)

**Comment by JMTrainee** [comment]
Hello, is there any updates on status of this bugfix? We really need this fix, as without this bugfix no iOS device can properly use this awesome plugin! ;/

**Review by JMTrainee — APPROVED** [review]

**Review by JMTrainee — APPROVED** [review]
This works nice on my iPhone.

**Comment by edualorobles** [comment]
It's this commit planned to be merged?

**Comment by nodro7** [comment]
Replaced by #1784

**Pull request closed without merging**
