### PR TITLE
(feat): Allow configuration of tick trimming on charts with [xy]-axis

### PR DESCRIPTION
**Pull request by clapis**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://github.com/swimlane/ngx-charts/issues/814

**What is the new behavior?**
Charts with [xy]-axis components now exposes 2 new properties to allow trimming configuration of tick's value: trimXAxisTicks (to enable/disable trimming) and maxXAxisTickLength (to set max length of tick).

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by MarcScheib** [comment]
Hi,
is there anything to do to support you in merging this? Would be nice to have this in a release as we are currently using a fork to have this feature.

Best Regards
Marc

**Comment by MarcScheib** [comment]
Hi,
is there anything to do to support you in merging this? Would be nice to have this in a release as we are currently using a fork to have this feature.

Best Regards
Marc

**Comment by MarcScheib** [comment]
Hi,
is there anything to do to support you in merging this? Would be nice to have this in a release as we are currently using a fork to have this feature.

Best Regards
Marc

**Comment by MarcScheib** [comment]
Hi,
is there anything to do to support you in merging this? Would be nice to have this in a release as we are currently using a fork to have this feature.

Best Regards
Marc

**Comment by MarcScheib** [comment]
Hi,
is there anything to do to support you in merging this? Would be nice to have this in a release as we are currently using a fork to have this feature.

Best Regards
Marc

**Comment by clapis** [comment]
@MarcScheib I believe at this point it's up to the maintainers having some time to look into it, not sure if I can do something to help - but let me know otherwise.

**Comment by faiyazkhan** [comment]
@clapis - Hi, can you please let me know if the branch is merged with the master or still waiting for maintainers.
Thanks,

**Comment by IVIyg0t** [comment]
@marjan-georgiev Would you mind reviewing this?  A lot of us need this feature.

**Comment by IVIyg0t** [comment]
@clapis Maybe if you add some of the maintainers to the reviewer's list they'll accept this PR?

**Comment by clapis** [comment]
> 
> 
> @clapis Maybe if you add some of the maintainers to the reviewer's list they'll accept this PR?

I can't do that. Pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository.

**Comment by marjan-georgiev** [comment]
Just got around to reviewing this. Overall it looks good. I noticed a couple of issues which I will be addressing post merge:
- Tick rotation does not take into consideration the trimmed length of the label
- Missing comma in chartTypes

 Thanks!

**Pull request merged**
