### PR TITLE
Fix embeds for new gitbook

### PR DESCRIPTION
**Pull request by Hypercubed**
**What kind of change does this PR introduce?** (check one with "x")
Fix docs

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Balagii** [comment]
Thanks for reinstating the examples in the docs! Unfortunately, many of the Plunkers don't run, but being able to see the code is still tremendously helpful.

**Comment by marjan-georgiev** [comment]
@Balagii we'll be updating those too.

**Comment by Hypercubed** [comment]
Yes, The examples are not compatible with ng 6.... we need to update each.  :(

**Comment by daddyschmack** [comment]
Hi Guys, the examples are no longerworking on stackblitz or plunkr

**Comment by karl-schelhammer-td** [comment]
I can't find any example code in any of the documentation either...

**Pull request merged**
