### PR TITLE
add  option to gauge to show or hide inner text

### PR DESCRIPTION
**Pull request by gnomeontherun**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

This adds a new option for gauges to disable the display of the inner text. Addresses: #230 

**What is the new behavior?**

New property `[showText]="true"` by default, but setting to false will hide the text.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by mikecabana** [comment]
@marjan-georgiev  @gnomeontherun Any update on this PR?

**Comment by digitalore** [comment]
Update?

**Comment by aferreiramartinez** [comment]
Any news on this feature?

**Comment by marjan-georgiev** [comment]
Thank you! I had to branch out to resolve the conflicts locally. Merged with this: https://github.com/swimlane/ngx-charts/pull/1175

**Pull request closed without merging**
