### PR TITLE
Sanitize tooltip labels

### PR DESCRIPTION
**Pull request by Minejima**
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
#1137 
Tooltip labels of the barchart is not escaped.

**What is the new behavior?**
Tooltip labels of the barchart is escaped.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by KingDarBoja** [comment]
@Minejima Everything is okay for the bar chart but the pie ones doesn't work at all.

Tried different characters wrapping around the labels and got this warning for `<<Germany>>` example: 
> WARNING: sanitizing HTML stripped some content

Can you take a look for the other charts, please? 

Cheers!

**Comment by Minejima** [comment]
@KingDarBoja Hi! I think I can fix everything.
The cause of this problem is passing the unescaped HTMLstring to the [innerHTML] Property.
Also, there is the same problem in demo, may I fix it in this PR?

**Comment by KingDarBoja** [comment]
@Minejima Yeah, you can go and fix the same issue for every chart that make use of tooltip labels. Same goes for demo page.

**Comment by KingDarBoja** [comment]
@Minejima Everything is fine but you missed the **Line-Chart** and the **Area-chart**.

image

@marjan-georgiev This PR is almost ready, looking forward for you review.

**Comment by Minejima** [comment]
Thank you for your check!
I fixed :D

**Comment by KingDarBoja** [comment]
> Thank you for your check!
> I fixed :D

There is one little bug missing, if you open the equation plot at the demo, you will see at the console this error:
`ERROR TypeError: label.replace is not a function at escapeLabel`.

Everything else is fine I think.

**Comment by Minejima** [comment]
That error occurred trying to access the replace method of number.

**Comment by marjan-georgiev** [comment]
Thanks @Minejima for the contribution, and m@KingDarBoja for the review!

**Pull request merged**
