### PR TITLE
rob sucks. we need a white bar.

### PR DESCRIPTION
**Pull request by annagebara**
team Austin!!

**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [X ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
you can't change the stroke color (why not??)

**What is the new behavior?**
stroke color defaults to white

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
im not sure how to test but im fairly certain this works and rocks

**Other information**:
pls help

### CODE REVIEW

**Comment by marjan-georgiev** [comment]
This changes the default behavior. If you want to make the stroke configurable, please define an input and set the default value to be 'none'.

**Comment by amcdnl** [comment]
Rob who? LOL

**Comment by Hypercubed** [comment]
Can stroke be applied via CSS instead of inlined... and therefore user overridable?

**Comment by marjan-georgiev** [comment]
@Hypercubed certainly. An input might provide more customization, if that's required.

I'll close this PR because there's another one addressing the same issue: https://github.com/swimlane/ngx-charts/pull/693

**Pull request closed without merging**
