### PR TITLE
Implemented legend positioning, fixes #135

### LINKED ISSUE #135: Legend Positions
Add ability to position the legend top|right|bottom|left.

### PR DESCRIPTION
**Pull request by flore2003**
Implemented legend positioning, with right and below as supported positions for the legend. Fixes #135.

**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
The legend is currently always displayed to the right of the chart

**What is the new behavior?**
Using the `legendPosition` input, the legend can now be shown either right or below the chart. It also opens the possibility to introduce other positions like above or left of the chart.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by bop10** [comment]
Hey, is this going to be merged?

**Comment by pathakparth** [comment]
Hi, can someone please provide status on this PR ? I am in need of this functionality at my current project. It is very nice feature to have.

Thanks.

**Comment by harellevy** [comment]
This feature will be awesome!!!
Is it going to be merged soon? looking forward for legend positioning 👍 🥇

**Comment by harellevy** [comment]
@achanta3215 I see a progress here. Will there be merged soon? please notice in the package.json file that the version is for 9+ (9.01?!)

**Comment by marjan-georgiev** [comment]
Thank you! Will be making slight adjustments (centering and horizontal scroll) before releasing.

**Comment by tobigit** [comment]
When setting legend position to 'below' and the chart should fit to container (no 'view'-attribute), the legend isnt visible. The chart uses the whole container height and the legend is invisible below the chart.
Does the height-calculation not take care of the legend height?

**Comment by rudifernandes** [comment]
Is it possible to set the legend position to top?
:/

**Pull request merged**
