### PR TITLE
Replace deep clone

### PR DESCRIPTION
**Pull request by Hypercubed**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by David-Mawer** [comment]
Um - so the publish failed for this merge.
I guess it's because the version number was not increased.

Could some-one please look into this for us?

**Comment by Hypercubed** [comment]
A new version has not yet been published.

**Comment by GrzegorzKaczan** [comment]
@Hypercubed  any ETA for the release?

**Comment by pauljanns** [comment]
Can this please be released? It's quite the important fix imo

**Comment by evtk** [comment]
Yes please, same here. We want to get rid of the deep clone, so please release this.

**Comment by pauljanns** [comment]
This is getting frustrating. I really like this project but probably best to use a fork for now. @marjan-georgiev

**Pull request merged**
