### PR TITLE
feat(tooltip): allow access to custom properties in tooltip templates

### PR DESCRIPTION
**Pull request by HitomiTenshi**
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

All Bar Chart types allow access to custom defined properties in tooltip templates.

Other charts don't.

**What is the new behavior?**

Fixes: #553

This PR follows the way Bar Charts implemented access to custom properties in tooltip templates and extends this functionality to the following chart types **(without making it a breaking change)**:

- Area Chart
- Area Chart Normalized
- Area Chart Stacked
- Line Chart
- Bubble Chart
- Polar Chart

**What do I mean with custom properties?**

Imagine you have the following data for polar charts:

```
[
  {
    "name": "Series 1",
    "series": [
      {
        "name": "Viscosity",
        "value": 80,
        "sourceValue": 1000
      },
      {
        "name": "Color",
        "value": 100,
        "sourceValue": 10
      }
    ]
  },
  {
    "name": "Series 2",
    "series": [
      {
        "name": "Viscosity",
        "value": 100,
        "sourceValue": 1250
      },
      {
        "name": "Color",
        "value": 50,
        "sourceValue": 5
      }
    ]
  }
]
```

The `value` property here is a calculated percentage while the `sourceValue` property holds the actual value. Usually you wouldn't be able to access this `sourceValue` property in tooltip templates (Bar Charts are the exception here).

This PR makes it so that you can access this property in tooltip templates, or any other arbitrary property you define.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by HitomiTenshi** [comment]
If anyone needs this PR urgently, I have included it in my `custom-build-next` branch, along with PR #359

Install with:

```
npm install github:HitomiTenshi/ngx-charts#custom-build-next --save
```

- Branch `custom-build-next` is using ngx-charts v6.0.2 (with this PR)

Please keep an eye out for the status of this PR and use the original `ngx-charts` library once this PR is in any way included in it.

@marjan-georgiev I'm open for a code review and will do changes if something is not to your liking.

**Comment by closer27** [comment]
Hi, I want this feature, but when will It be merged?

**Comment by agecas** [comment]
Guys any updated on this?

**Comment by vjpc** [comment]
Hi,

Can this functionality be extended to pie-chart also?

Thanks

**Comment by sschocke** [comment]
Yes please. I need this feature to customize the tooltip on a line chart that displays the maximum and minimum as well. This is a built-in feature of the line chart, and it shows the range when using the default template, but I can't access the data because the model passed to a custom template does not contain min & max.

**Comment by HitomiTenshi** [comment]
I have been upgrading my projects recently and I decided to create a new custom ngx-charts build **with this PR**. In case anyone is interested, you can get a fresh build here:

```
npm install github:HitomiTenshi/ngx-charts#angular61 --save
```

Build based on `v9.0.0`. This build includes only this PR:

- PR #555 (this one)

You can see my commits here at the top:
https://github.com/HitomiTenshi/ngx-charts/commits/angular61

**Comment by HitomiTenshi** [comment]
I made a new build:

```
npm install github:HitomiTenshi/ngx-charts#angular7 --save
```

Build based on `v10.0.0`. This build includes only this PR:

- PR #555 (this one)

You can see my commits here at the top:
https://github.com/HitomiTenshi/ngx-charts/commits/angular7

**Comment by markriser** [comment]
@HitomiTenshi Thanks very much for your work on this-- reviewing the changes though-- I don't see any changes to the line chart source. How does the change work for line charts then?

Thanks!
Mark

**Comment by HitomiTenshi** [comment]
@markriser I think `CircleSeriesComponent` in `src/common/circle-series.component.ts` is being utilized in line charts. I could be wrong though. If this PR is not working with line charts I'll take another look.

**Comment by markriser** [comment]
Hey @HitomiTenshi - I just pulled and installed your build. Indeed, it does work for the point tooltip, but not for the series tooltip, which appears with just the 'name', 'value', 'series', and 'color'... I'm not too familiar with the internal structure of ngx-charts... Any idea where to add this for the series tooltip? Thank you again!

**Comment by HitomiTenshi** [comment]
@markriser I think I know what you mean, I might've overlooked that. I'll add it in a moment.

**Comment by markriser** [comment]
@HitomiTenshi Also, you might want to pull from master, as there is a vulnerability in event-stream. 

https://github.com/swimlane/ngx-charts/issues/1047

**Comment by HitomiTenshi** [comment]
@markriser Already did that 👍

**Comment by markriser** [comment]
@HitomiTenshi I believe these lines could be modified so that the item is copied, rather than only specific values being populated in the series results... 

https://github.com/HitomiTenshi/ngx-charts/blob/81e9158998b1ef44d633cc1dfc0fcf6a32e9cd63/src/common/tooltip-area.component.ts#L131-L138

I'd suggest copying, not just using the item reference, since changes made would then corrupt the series data.

**Comment by HitomiTenshi** [comment]
@markriser I'm using `Object.assign` now to assign to a new object instead of modifying the original. I wrote this code a year ago. Looking at it now I realise I didn't solve it properly 😄 

And yeah I already found the file in question. I'm working on an update right now.

**Comment by HitomiTenshi** [comment]
New build with the event-stream vulnerability removed and the code changes I did today. `seriesTooltipTemplates` should work as well now.

```
npm install github:HitomiTenshi/ngx-charts#angular71 --save
```

Build based on `v10.0.0`. This build includes only this PR:

- PR #555 (this one)

You can see my commits here at the top:
https://github.com/HitomiTenshi/ngx-charts/commits/angular71

**Comment by crtjer** [comment]
@marjan-georgiev Can this be merged in yet?

**Comment by mihelcicj** [comment]
It's been over a year and this functionality is still missing. Can this be merged in yet please.

**Comment by marjan-georgiev** [comment]
Thank you!

**Pull request merged**
