### PR TITLE
Upgrade project and library with Angular 10 dependencies

### PR DESCRIPTION
**Pull request by linjie997**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe: Upgrade project and library to Angular 10

**What is the current behavior?** (You can also link to an open issue here)
https://github.com/swimlane/ngx-charts/issues/1467

**What is the new behavior?**
Error is gone since the library is now build with Angular 10> 

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
No breaking changes

**Other information**:

### CODE REVIEW

**Comment by marjan-georgiev** [comment]
Thanks! Looks like prettier check failed. To fix, you can run `npm run prettier`

**Comment by linjie997** [comment]
Done, the prettier check is not passed!

**Comment by marjan-georgiev** [comment]
Thank you! 👍

**Comment by trickeyone** [comment]
@marjan-georgiev Do you have an ETA on when a release with this will be done?

**Comment by BLSully** [comment]
Looking for this update too so I can do my angular 10 update. Thanks!

**Comment by marjan-georgiev** [comment]
Released in v16.0.0. Thanks for the patience everyone!

**Pull request merged**
