### PR TITLE
(release): 19.1.1-Added roundEdges to vertical and horizontal stacked

### PR DESCRIPTION
**Pull request by Uchehens**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Added the roundEdges feature for ngx-charts-bar-vertical-stacked and  ngx-charts-bar-horizontal-stacked component #835 

**What is the new behavior?**
The ngx-charts-bar-vertical-stacked and  ngx-charts-bar-horizontal-stacked chart now have roundEdges boolean property to enable and disable the rounded Edge features on the chart respectively. It is false by default

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by cyrilferte** [comment]
why this PR is not merge ?

**Comment by Uchehens** [comment]
>

**Comment by todorpavlovic** [comment]
Is this getting released ?

**Comment by bascoruben** [comment]
Updates on this please?

**Comment by Uchehens** [comment]
No one is reviewing it

**Pull request closed without merging**
